part of game_parking;

// http://jsonformatter.curiousconcept.com/

var gameParkingModelJson = r'''
{
   "width":990,
   "lines":[
      {
         "box2box1Min":"1",
         "box1Name":"Area",
         "box1box2Min":"0",
         "box2Name":"Parking",
         "category":"relationship",
         "box2box1Id":true,
         "box2box1Name":"area",
         "box1box2Id":false,
         "box1box2Name":"parkings",
         "box1box2Max":"N",
         "internal":true,
         "box2box1Max":"1"
      },
      {
         "box2box1Min":"1",
         "box1Name":"Brand",
         "box1box2Min":"0",
         "box2Name":"Car",
         "category":"relationship",
         "box2box1Id":true,
         "box2box1Name":"brand",
         "box1box2Id":false,
         "box1box2Name":"cars",
         "box1box2Max":"N",
         "internal":true,
         "box2box1Max":"1"
      },
      {
         "box2box1Min":"1",
         "box1Name":"Parking",
         "box1box2Min":"0",
         "box2Name":"Car",
         "category":"relationship",
         "box2box1Id":true,
         "box2box1Name":"parking",
         "box1box2Id":false,
         "box1box2Name":"cars",
         "box1box2Max":"N",
         "internal":true,
         "box2box1Max":"1"
      }
   ],
   "height":580,
   "boxes":[
      {
         "entry":true,
         "name":"Area",
         "x":74,
         "y":53,
         "width":80,
         "height":80,
         "items":[
            {
               "sequence":10,
               "category":"identifier",
               "name":"name",
               "type":"String",
               "init":""
            }
         ]
      },
      {
         "entry":true,
         "name":"Brand",
         "x":205,
         "y":53,
         "width":80,
         "height":140,
         "items":[
            {
               "sequence":10,
               "category":"identifier",
               "name":"name",
               "type":"String",
               "init":""
            },
            {
               "sequence":20,
               "category":"required",
               "name":"length",
               "type":"int",
               "init":"2"
            },
            {
               "sequence":30,
               "category":"required",
               "name":"colorName",
               "type":"String",
               "init":""
            },
            {
               "sequence":40,
               "category":"required",
               "name":"color",
               "type":"String",
               "init":""
            },
            {
               "sequence":50,
               "category":"attribute",
               "name":"red",
               "type":"String",
               "init":""
            },
            {
               "sequence":60,
               "category":"attribute",
               "name":"green",
               "type":"String",
               "init":""
            },
            {
               "sequence":70,
               "category":"attribute",
               "name":"blue",
               "type":"String",
               "init":""
            }
         ]
      },
      {
         "entry":true,
         "name":"Parking",
         "x":69,
         "y":249,
         "width":80,
         "height":80,
         "items":[
            {
               "sequence":10,
               "category":"identifier",
               "name":"number",
               "type":"int",
               "init":""
            }
         ]
      },
      {
         "entry":false,
         "name":"Car",
         "x":354,
         "y":302,
         "width":100,
         "height":120,
         "items":[
            {
               "sequence":10,
               "category":"required",
               "name":"orientation",
               "type":"String",
               "init":"horizontal"
            },
            {
               "sequence":20,
               "category":"required",
               "name":"startRow",
               "type":"int",
               "init":""
            },
            {
               "sequence":30,
               "category":"required",
               "name":"startColumn",
               "type":"int",
               "init":""
            },
            {
               "sequence":40,
               "category":"required",
               "name":"currentRow",
               "type":"int",
               "init":""
            },
            {
               "sequence":50,
               "category":"required",
               "name":"currentColumn",
               "type":"int",
               "init":""
            },
            {
               "sequence":60,
               "category":"attribute",
               "name":"selected",
               "type":"bool",
               "init":"false"
            }
         ]
      }
   ]
}
''';


