part of game_parking;

// http://jsonformatter.curiousconcept.com/

var gameParkingDataJson = r'''
{
   "domain":"Car",
   "entries":[
      {
         "concept":"Area",
         "entities":[
            {
               "oid":"1346543098800",
               "name":"beginner",
               "parkings":[
                  {
                     "cars":[
                        {
                           "parking":"1346543098802",
                           "startRow":"0",
                           "oid":"1346543098808",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"0",
                           "orientation":"horizontal",
                           "brand":"1346543098771",
                           "code":null
                        },
                        {
                           "parking":"1346543098802",
                           "startRow":"4",
                           "oid":"1346543098810",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"4",
                           "currentColumn":"0",
                           "orientation":"vertical",
                           "brand":"1346543098776",
                           "code":null
                        },
                        {
                           "parking":"1346543098802",
                           "startRow":"4",
                           "oid":"1346543098812",
                           "startColumn":"4",
                           "selected":"false",
                           "currentRow":"4",
                           "currentColumn":"4",
                           "orientation":"horizontal",
                           "brand":"1346543098777",
                           "code":null
                        },
                        {
                           "parking":"1346543098802",
                           "startRow":"0",
                           "oid":"1346543098814",
                           "startColumn":"5",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"5",
                           "orientation":"vertical",
                           "brand":"1346543098790",
                           "code":null
                        },
                        {
                           "parking":"1346543098802",
                           "startRow":"1",
                           "oid":"1346543098816",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"1",
                           "currentColumn":"0",
                           "orientation":"vertical",
                           "brand":"1346543098793",
                           "code":null
                        },
                        {
                           "parking":"1346543098802",
                           "startRow":"1",
                           "oid":"1346543098818",
                           "startColumn":"3",
                           "selected":"false",
                           "currentRow":"1",
                           "currentColumn":"3",
                           "orientation":"vertical",
                           "brand":"1346543098795",
                           "code":null
                        },
                        {
                           "parking":"1346543098802",
                           "startRow":"5",
                           "oid":"1346543098819",
                           "startColumn":"2",
                           "selected":"false",
                           "currentRow":"5",
                           "currentColumn":"2",
                           "orientation":"horizontal",
                           "brand":"1346543098796",
                           "code":null
                        },
                        {
                           "parking":"1346543098802",
                           "startRow":"2",
                           "oid":"1346543098822",
                           "startColumn":"1",
                           "selected":"false",
                           "currentRow":"2",
                           "currentColumn":"1",
                           "orientation":"horizontal",
                           "brand":"1346543098798",
                           "code":null
                        }
                     ],
                     "area":"1346543098800",
                     "oid":"1346543098802",
                     "number":"1",
                     "code":null
                  },
                  {
                     "cars":[
                        {
                           "parking":"1346543098824",
                           "startRow":"0",
                           "oid":"1346543098827",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"0",
                           "orientation":"vertical",
                           "brand":"1346543098771",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"1",
                           "oid":"1346543098828",
                           "startColumn":"3",
                           "selected":"false",
                           "currentRow":"1",
                           "currentColumn":"3",
                           "orientation":"vertical",
                           "brand":"1346543098776",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"2",
                           "oid":"1346543098830",
                           "startColumn":"4",
                           "selected":"false",
                           "currentRow":"2",
                           "currentColumn":"4",
                           "orientation":"vertical",
                           "brand":"1346543098777",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"4",
                           "oid":"1346543098831",
                           "startColumn":"2",
                           "selected":"false",
                           "currentRow":"4",
                           "currentColumn":"2",
                           "orientation":"vertical",
                           "brand":"1346543098778",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"4",
                           "oid":"1346543098834",
                           "startColumn":"4",
                           "selected":"false",
                           "currentRow":"4",
                           "currentColumn":"4",
                           "orientation":"horizontal",
                           "brand":"1346543098780",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"5",
                           "oid":"1346543098835",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"5",
                           "currentColumn":"0",
                           "orientation":"horizontal",
                           "brand":"1346543098781",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"5",
                           "oid":"1346543098837",
                           "startColumn":"3",
                           "selected":"false",
                           "currentRow":"5",
                           "currentColumn":"3",
                           "orientation":"horizontal",
                           "brand":"1346543098783",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"0",
                           "oid":"1346543098839",
                           "startColumn":"3",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"3",
                           "orientation":"horizontal",
                           "brand":"1346543098790",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"1",
                           "oid":"1346543098841",
                           "startColumn":"5",
                           "selected":"false",
                           "currentRow":"1",
                           "currentColumn":"5",
                           "orientation":"vertical",
                           "brand":"1346543098793",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"3",
                           "oid":"1346543098842",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"3",
                           "currentColumn":"0",
                           "orientation":"horizontal",
                           "brand":"1346543098795",
                           "code":null
                        },
                        {
                           "parking":"1346543098824",
                           "startRow":"2",
                           "oid":"1346543098844",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"2",
                           "currentColumn":"0",
                           "orientation":"horizontal",
                           "brand":"1346543098798",
                           "code":null
                        }
                     ],
                     "area":"1346543098800",
                     "oid":"1346543098824",
                     "number":"2",
                     "code":null
                  }
               ],
               "code":null
            },
            {
               "oid":"1346543098846",
               "name":"intermediate",
               "parkings":[
                  {
                     "cars":[
                        {
                           "parking":"1346543098847",
                           "startRow":"0",
                           "oid":"1346543098850",
                           "startColumn":"1",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"1",
                           "orientation":"horizontal",
                           "brand":"1346543098771",
                           "code":null
                        },
                        {
                           "parking":"1346543098847",
                           "startRow":"3",
                           "oid":"1346543098852",
                           "startColumn":"2",
                           "selected":"false",
                           "currentRow":"3",
                           "currentColumn":"2",
                           "orientation":"vertical",
                           "brand":"1346543098776",
                           "code":null
                        },
                        {
                           "parking":"1346543098847",
                           "startRow":"4",
                           "oid":"1346543098853",
                           "startColumn":"5",
                           "selected":"false",
                           "currentRow":"4",
                           "currentColumn":"5",
                           "orientation":"vertical",
                           "brand":"1346543098780",
                           "code":null
                        },
                        {
                           "parking":"1346543098847",
                           "startRow":"0",
                           "oid":"1346543098855",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"0",
                           "orientation":"vertical",
                           "brand":"1346543098790",
                           "code":null
                        },
                        {
                           "parking":"1346543098847",
                           "startRow":"0",
                           "oid":"1346543098857",
                           "startColumn":"3",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"3",
                           "orientation":"vertical",
                           "brand":"1346543098793",
                           "code":null
                        },
                        {
                           "parking":"1346543098847",
                           "startRow":"3",
                           "oid":"1346543098858",
                           "startColumn":"3",
                           "selected":"false",
                           "currentRow":"3",
                           "currentColumn":"3",
                           "orientation":"horizontal",
                           "brand":"1346543098795",
                           "code":null
                        },
                        {
                           "parking":"1346543098847",
                           "startRow":"5",
                           "oid":"1346543098860",
                           "startColumn":"2",
                           "selected":"false",
                           "currentRow":"5",
                           "currentColumn":"2",
                           "orientation":"horizontal",
                           "brand":"1346543098796",
                           "code":null
                        },
                        {
                           "parking":"1346543098847",
                           "startRow":"2",
                           "oid":"1346543098862",
                           "startColumn":"1",
                           "selected":"false",
                           "currentRow":"2",
                           "currentColumn":"1",
                           "orientation":"horizontal",
                           "brand":"1346543098798",
                           "code":null
                        }
                     ],
                     "area":"1346543098846",
                     "oid":"1346543098847",
                     "number":"1",
                     "code":null
                  },
                  {
                     "cars":[
                        {
                           "parking":"1346543098863",
                           "startRow":"0",
                           "oid":"1346543098866",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"0",
                           "orientation":"vertical",
                           "brand":"1346543098771",
                           "code":null
                        },
                        {
                           "parking":"1346543098863",
                           "startRow":"0",
                           "oid":"1346543098867",
                           "startColumn":"1",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"1",
                           "orientation":"horizontal",
                           "brand":"1346543098776",
                           "code":null
                        },
                        {
                           "parking":"1346543098863",
                           "startRow":"4",
                           "oid":"1346543098869",
                           "startColumn":"4",
                           "selected":"false",
                           "currentRow":"4",
                           "currentColumn":"4",
                           "orientation":"vertical",
                           "brand":"1346543098777",
                           "code":null
                        },
                        {
                           "parking":"1346543098863",
                           "startRow":"0",
                           "oid":"1346543098870",
                           "startColumn":"5",
                           "selected":"false",
                           "currentRow":"0",
                           "currentColumn":"5",
                           "orientation":"vertical",
                           "brand":"1346543098790",
                           "code":null
                        },
                        {
                           "parking":"1346543098863",
                           "startRow":"1",
                           "oid":"1346543098872",
                           "startColumn":"2",
                           "selected":"false",
                           "currentRow":"1",
                           "currentColumn":"2",
                           "orientation":"vertical",
                           "brand":"1346543098793",
                           "code":null
                        },
                        {
                           "parking":"1346543098863",
                           "startRow":"3",
                           "oid":"1346543098873",
                           "startColumn":"3",
                           "selected":"false",
                           "currentRow":"3",
                           "currentColumn":"3",
                           "orientation":"horizontal",
                           "brand":"1346543098795",
                           "code":null
                        },
                        {
                           "parking":"1346543098863",
                           "startRow":"5",
                           "oid":"1346543098875",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"5",
                           "currentColumn":"0",
                           "orientation":"horizontal",
                           "brand":"1346543098796",
                           "code":null
                        },
                        {
                           "parking":"1346543098863",
                           "startRow":"2",
                           "oid":"1346543098877",
                           "startColumn":"0",
                           "selected":"false",
                           "currentRow":"2",
                           "currentColumn":"0",
                           "orientation":"horizontal",
                           "brand":"1346543098798",
                           "code":null
                        }
                     ],
                     "area":"1346543098846",
                     "oid":"1346543098863",
                     "number":"2",
                     "code":null
                  }
               ],
               "code":null
            }
         ]
      },
      {
         "concept":"Brand",
         "entities":[
            {
               "green":"204",
               "length":"2",
               "color":"#66CC99",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"0",
                     "oid":"1346543098808",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098771",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"0",
                     "oid":"1346543098827",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098771",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"0",
                     "oid":"1346543098850",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098771",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"0",
                     "oid":"1346543098866",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098771",
                     "code":null
                  }
               ],
               "oid":"1346543098771",
               "name":"A",
               "colorName":"green",
               "blue":"153",
               "red":"102",
               "code":null
            },
            {
               "green":"204",
               "length":"2",
               "color":"#FFCC66",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"4",
                     "oid":"1346543098810",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098776",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"1",
                     "oid":"1346543098828",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"3",
                     "orientation":"vertical",
                     "brand":"1346543098776",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"3",
                     "oid":"1346543098852",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"2",
                     "orientation":"vertical",
                     "brand":"1346543098776",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"0",
                     "oid":"1346543098867",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098776",
                     "code":null
                  }
               ],
               "oid":"1346543098776",
               "name":"B",
               "colorName":"orange",
               "blue":"102",
               "red":"255",
               "code":null
            },
            {
               "green":"255",
               "length":"2",
               "color":"#00FFFF",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"4",
                     "oid":"1346543098812",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"4",
                     "orientation":"horizontal",
                     "brand":"1346543098777",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"2",
                     "oid":"1346543098830",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"4",
                     "orientation":"vertical",
                     "brand":"1346543098777",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"4",
                     "oid":"1346543098869",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"4",
                     "orientation":"vertical",
                     "brand":"1346543098777",
                     "code":null
                  }
               ],
               "oid":"1346543098777",
               "name":"C",
               "colorName":"cyan",
               "blue":"255",
               "red":"0",
               "code":null
            },
            {
               "green":"153",
               "length":"2",
               "color":"#FF99CC",
               "cars":[
                  {
                     "parking":"1346543098824",
                     "startRow":"4",
                     "oid":"1346543098831",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"2",
                     "orientation":"vertical",
                     "brand":"1346543098778",
                     "code":null
                  }
               ],
               "oid":"1346543098778",
               "name":"D",
               "colorName":"light pink",
               "blue":"204",
               "red":"255",
               "code":null
            },
            {
               "green":"0",
               "length":"2",
               "color":"#660033",
               "cars":[
                  {
                     "parking":"1346543098824",
                     "startRow":"4",
                     "oid":"1346543098834",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"4",
                     "orientation":"horizontal",
                     "brand":"1346543098780",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"4",
                     "oid":"1346543098853",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098780",
                     "code":null
                  }
               ],
               "oid":"1346543098780",
               "name":"E",
               "colorName":"dark magenta",
               "blue":"51",
               "red":"102",
               "code":null
            },
            {
               "green":"153",
               "length":"2",
               "color":"#009966",
               "cars":[
                  {
                     "parking":"1346543098824",
                     "startRow":"5",
                     "oid":"1346543098835",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098781",
                     "code":null
                  }
               ],
               "oid":"1346543098781",
               "name":"F",
               "colorName":"dark green",
               "blue":"102",
               "red":"0",
               "code":null
            },
            {
               "green":"190",
               "length":"2",
               "color":"#BEBEBE",
               "cars":[
                  {
                     "parking":"1346543098824",
                     "startRow":"5",
                     "oid":"1346543098837",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098783",
                     "code":null
                  }
               ],
               "oid":"1346543098783",
               "name":"G",
               "colorName":"gray",
               "blue":"190",
               "red":"190",
               "code":null
            },
            {
               "green":"153",
               "length":"2",
               "color":"#FF9966",
               "cars":[

               ],
               "oid":"1346543098784",
               "name":"H",
               "colorName":"peach",
               "blue":"102",
               "red":"255",
               "code":null
            },
            {
               "green":"211",
               "length":"2",
               "color":"#D3D3D3",
               "cars":[

               ],
               "oid":"1346543098785",
               "name":"I",
               "colorName":"light gray",
               "blue":"211",
               "red":"211",
               "code":null
            },
            {
               "green":"102",
               "length":"2",
               "color":"#996600",
               "cars":[

               ],
               "oid":"1346543098787",
               "name":"J",
               "colorName":"brown",
               "blue":"0",
               "red":"153",
               "code":null
            },
            {
               "green":"153",
               "length":"2",
               "color":"#CC9900",
               "cars":[

               ],
               "oid":"1346543098788",
               "name":"K",
               "colorName":"mustard",
               "blue":"0",
               "red":"204",
               "code":null
            },
            {
               "green":"255",
               "length":"3",
               "color":"#FFFF99",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"0",
                     "oid":"1346543098814",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098790",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"0",
                     "oid":"1346543098839",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098790",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"0",
                     "oid":"1346543098855",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098790",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"0",
                     "oid":"1346543098870",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098790",
                     "code":null
                  }
               ],
               "oid":"1346543098790",
               "name":"O",
               "colorName":"light yellow",
               "blue":"153",
               "red":"255",
               "code":null
            },
            {
               "green":"51",
               "length":"3",
               "color":"#993366",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"1",
                     "oid":"1346543098816",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"1",
                     "oid":"1346543098841",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"0",
                     "oid":"1346543098857",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"3",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"1",
                     "oid":"1346543098872",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"2",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  }
               ],
               "oid":"1346543098793",
               "name":"P",
               "colorName":"magenta",
               "blue":"102",
               "red":"153",
               "code":null
            },
            {
               "green":"153",
               "length":"3",
               "color":"#6699CC",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"1",
                     "oid":"1346543098818",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"3",
                     "orientation":"vertical",
                     "brand":"1346543098795",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"3",
                     "oid":"1346543098842",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098795",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"3",
                     "oid":"1346543098858",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098795",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"3",
                     "oid":"1346543098873",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098795",
                     "code":null
                  }
               ],
               "oid":"1346543098795",
               "name":"Q",
               "colorName":"gray blue",
               "blue":"204",
               "red":"102",
               "code":null
            },
            {
               "green":"191",
               "length":"3",
               "color":"#00BFFF",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"5",
                     "oid":"1346543098819",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"2",
                     "orientation":"horizontal",
                     "brand":"1346543098796",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"5",
                     "oid":"1346543098860",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"2",
                     "orientation":"horizontal",
                     "brand":"1346543098796",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"5",
                     "oid":"1346543098875",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098796",
                     "code":null
                  }
               ],
               "oid":"1346543098796",
               "name":"R",
               "colorName":"deep sky blue",
               "blue":"255",
               "red":"0",
               "code":null
            },
            {
               "green":"0",
               "length":"2",
               "color":"#CC0033",
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"2",
                     "oid":"1346543098822",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"2",
                     "oid":"1346543098844",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"2",
                     "oid":"1346543098862",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"2",
                     "oid":"1346543098877",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  }
               ],
               "oid":"1346543098798",
               "name":"X",
               "colorName":"red",
               "blue":"51",
               "red":"204",
               "code":null
            }
         ]
      },
      {
         "concept":"Parking",
         "entities":[
            {
               "cars":[
                  {
                     "parking":"1346543098802",
                     "startRow":"0",
                     "oid":"1346543098808",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098771",
                     "code":null
                  },
                  {
                     "parking":"1346543098802",
                     "startRow":"4",
                     "oid":"1346543098810",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098776",
                     "code":null
                  },
                  {
                     "parking":"1346543098802",
                     "startRow":"4",
                     "oid":"1346543098812",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"4",
                     "orientation":"horizontal",
                     "brand":"1346543098777",
                     "code":null
                  },
                  {
                     "parking":"1346543098802",
                     "startRow":"0",
                     "oid":"1346543098814",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098790",
                     "code":null
                  },
                  {
                     "parking":"1346543098802",
                     "startRow":"1",
                     "oid":"1346543098816",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  },
                  {
                     "parking":"1346543098802",
                     "startRow":"1",
                     "oid":"1346543098818",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"3",
                     "orientation":"vertical",
                     "brand":"1346543098795",
                     "code":null
                  },
                  {
                     "parking":"1346543098802",
                     "startRow":"5",
                     "oid":"1346543098819",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"2",
                     "orientation":"horizontal",
                     "brand":"1346543098796",
                     "code":null
                  },
                  {
                     "parking":"1346543098802",
                     "startRow":"2",
                     "oid":"1346543098822",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  }
               ],
               "area":"1346543098800",
               "oid":"1346543098802",
               "number":"1",
               "code":null
            },
            {
               "cars":[
                  {
                     "parking":"1346543098824",
                     "startRow":"0",
                     "oid":"1346543098827",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098771",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"1",
                     "oid":"1346543098828",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"3",
                     "orientation":"vertical",
                     "brand":"1346543098776",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"2",
                     "oid":"1346543098830",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"4",
                     "orientation":"vertical",
                     "brand":"1346543098777",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"4",
                     "oid":"1346543098831",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"2",
                     "orientation":"vertical",
                     "brand":"1346543098778",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"4",
                     "oid":"1346543098834",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"4",
                     "orientation":"horizontal",
                     "brand":"1346543098780",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"5",
                     "oid":"1346543098835",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098781",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"5",
                     "oid":"1346543098837",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098783",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"0",
                     "oid":"1346543098839",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098790",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"1",
                     "oid":"1346543098841",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"3",
                     "oid":"1346543098842",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098795",
                     "code":null
                  },
                  {
                     "parking":"1346543098824",
                     "startRow":"2",
                     "oid":"1346543098844",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  }
               ],
               "area":"1346543098800",
               "oid":"1346543098824",
               "number":"2",
               "code":null
            },
            {
               "cars":[
                  {
                     "parking":"1346543098847",
                     "startRow":"0",
                     "oid":"1346543098850",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098771",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"3",
                     "oid":"1346543098852",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"2",
                     "orientation":"vertical",
                     "brand":"1346543098776",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"4",
                     "oid":"1346543098853",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098780",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"0",
                     "oid":"1346543098855",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098790",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"0",
                     "oid":"1346543098857",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"3",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"3",
                     "oid":"1346543098858",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098795",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"5",
                     "oid":"1346543098860",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"2",
                     "orientation":"horizontal",
                     "brand":"1346543098796",
                     "code":null
                  },
                  {
                     "parking":"1346543098847",
                     "startRow":"2",
                     "oid":"1346543098862",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  }
               ],
               "area":"1346543098846",
               "oid":"1346543098847",
               "number":"1",
               "code":null
            },
            {
               "cars":[
                  {
                     "parking":"1346543098863",
                     "startRow":"0",
                     "oid":"1346543098866",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"0",
                     "orientation":"vertical",
                     "brand":"1346543098771",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"0",
                     "oid":"1346543098867",
                     "startColumn":"1",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"1",
                     "orientation":"horizontal",
                     "brand":"1346543098776",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"4",
                     "oid":"1346543098869",
                     "startColumn":"4",
                     "selected":"false",
                     "currentRow":"4",
                     "currentColumn":"4",
                     "orientation":"vertical",
                     "brand":"1346543098777",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"0",
                     "oid":"1346543098870",
                     "startColumn":"5",
                     "selected":"false",
                     "currentRow":"0",
                     "currentColumn":"5",
                     "orientation":"vertical",
                     "brand":"1346543098790",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"1",
                     "oid":"1346543098872",
                     "startColumn":"2",
                     "selected":"false",
                     "currentRow":"1",
                     "currentColumn":"2",
                     "orientation":"vertical",
                     "brand":"1346543098793",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"3",
                     "oid":"1346543098873",
                     "startColumn":"3",
                     "selected":"false",
                     "currentRow":"3",
                     "currentColumn":"3",
                     "orientation":"horizontal",
                     "brand":"1346543098795",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"5",
                     "oid":"1346543098875",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"5",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098796",
                     "code":null
                  },
                  {
                     "parking":"1346543098863",
                     "startRow":"2",
                     "oid":"1346543098877",
                     "startColumn":"0",
                     "selected":"false",
                     "currentRow":"2",
                     "currentColumn":"0",
                     "orientation":"horizontal",
                     "brand":"1346543098798",
                     "code":null
                  }
               ],
               "area":"1346543098846",
               "oid":"1346543098863",
               "number":"2",
               "code":null
            }
         ]
      }
   ],
   "model":"Parking"
}
''';
