part of game_parking;

// http://jsonformatter.curiousconcept.com/

var gameParkingModelJson = r'''
{
    "width":990,
    "lines":[
        {
            "box2box1Max":"1",
            "box1Name":"Area",
            "box1box2Min":"0",
            "box2Name":"Parking",
            "box1box2Id":false,
            "box2box1Id":true,
            "box2box1Name":"area",
            "box1box2Max":"N",
            "box1box2Name":"parkings",
            "box2box1Min":"1",
            "category":"relationship",
            "internal":false
        },
        {
            "box2box1Max":"1",
            "box1Name":"Brand",
            "box1box2Min":"0",
            "box2Name":"Car",
            "box1box2Id":false,
            "box2box1Id":true,
            "box2box1Name":"brand",
            "box1box2Max":"N",
            "box1box2Name":"cars",
            "box2box1Min":"1",
            "category":"relationship",
            "internal":false
        },
        {
            "box2box1Max":"1",
            "box1Name":"Parking",
            "box1box2Min":"0",
            "box2Name":"Car",
            "box1box2Id":false,
            "box2box1Id":true,
            "box2box1Name":"parking",
            "box1box2Max":"N",
            "box1box2Name":"cars",
            "box2box1Min":"1",
            "category":"relationship",
            "internal":true
        }
    ],
    "height":580,
    "boxes":[
        {
            "width":80,
            "entry":true,
            "name":"Area",
            "x":74,
            "height":80,
            "y":53,
            "items":[
                {
                    "sequence":10,
                    "name":"name",
                    "init":"",
                    "essential":true,
                    "sensitive":false,
                    "category":"identifier",
                    "type":"String"
                }
            ]
        },
        {
            "width":80,
            "entry":true,
            "name":"Brand",
            "x":205,
            "height":140,
            "y":53,
            "items":[
                {
                    "sequence":10,
                    "name":"name",
                    "init":"",
                    "essential":true,
                    "sensitive":false,
                    "category":"identifier",
                    "type":"String"
                },
                {
                    "sequence":20,
                    "name":"length",
                    "init":"2",
                    "essential":true,
                    "sensitive":false,
                    "category":"required",
                    "type":"int"
                },
                {
                    "sequence":30,
                    "name":"colorName",
                    "init":"",
                    "essential":true,
                    "sensitive":false,
                    "category":"required",
                    "type":"String"
                },
                {
                    "sequence":40,
                    "name":"color",
                    "init":"",
                    "essential":true,
                    "sensitive":false,
                    "category":"required",
                    "type":"String"
                },
                {
                    "sequence":50,
                    "name":"red",
                    "init":"",
                    "essential":false,
                    "sensitive":false,
                    "category":"attribute",
                    "type":"int"
                },
                {
                    "sequence":60,
                    "name":"green",
                    "init":"",
                    "essential":false,
                    "sensitive":false,
                    "category":"attribute",
                    "type":"int"
                },
                {
                    "sequence":70,
                    "name":"blue",
                    "init":"",
                    "essential":false,
                    "sensitive":false,
                    "category":"attribute",
                    "type":"int"
                }
            ]
        },
        {
            "width":80,
            "entry":true,
            "name":"Parking",
            "x":69,
            "height":80,
            "y":249,
            "items":[
                {
                    "sequence":10,
                    "name":"number",
                    "init":"",
                    "essential":true,
                    "sensitive":false,
                    "category":"identifier",
                    "type":"int"
                }
            ]
        },
        {
            "width":100,
            "entry":false,
            "name":"Car",
            "x":354,
            "height":120,
            "y":302,
            "items":[
                {
                    "sequence":10,
                    "name":"orientation",
                    "init":"horizontal",
                    "essential":true,
                    "sensitive":false,
                    "category":"required",
                    "type":"String"
                },
                {
                    "sequence":20,
                    "name":"startRow",
                    "init":"",
                    "essential":true,
                    "sensitive":false,
                    "category":"required",
                    "type":"int"
                },
                {
                    "sequence":30,
                    "name":"startColumn",
                    "init":"",
                    "essential":true,
                    "sensitive":false,
                    "category":"required",
                    "type":"int"
                },
                {
                    "sequence":40,
                    "name":"currentRow",
                    "init":"",
                    "essential":false,
                    "sensitive":false,
                    "category":"required",
                    "type":"int"
                },
                {
                    "sequence":50,
                    "name":"currentColumn",
                    "init":"",
                    "essential":false,
                    "sensitive":false,
                    "category":"required",
                    "type":"int"
                },
                {
                    "sequence":60,
                    "name":"selected",
                    "init":"false",
                    "essential":false,
                    "sensitive":false,
                    "category":"attribute",
                    "type":"bool"
                }
            ]
        }
    ]
}
''';


