part of dartling_types;

// http://www.json.org/
// http://jsonformatter.curiousconcept.com/

// lib/dartling/types/json/model.dart

var dartlingTypesModelJson = r'''
{
   "width":990,
   "height":580,
   "boxes":[
      {
         "name":"Type",
         "entry":true,
         "x":207,
         "y":236,
         "width":120,
         "height":200,
         "items":[
            {
               "sequence":10,
               "name":"sequence",
               "category":"identifier",
               "type":"int",
               "init":"increment",
               "essential":true,
               "sensitive":false
            },
            {
               "sequence":20,
               "name":"title",
               "category":"required",
               "type":"String",
               "init":"",
               "essential":true,
               "sensitive":false
            },
            {
               "sequence":30,
               "name":"email",
               "category":"attribute",
               "type":"Email",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":40,
               "name":"started",
               "category":"attribute",
               "type":"DateTime",
               "init":"now",
               "essential":true,
               "sensitive":false
            },
            {
               "sequence":50,
               "name":"price",
               "category":"attribute",
               "type":"double",
               "init":"0",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":60,
               "name":"qty",
               "category":"attribute",
               "type":"num",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":70,
               "name":"completed",
               "category":"attribute",
               "type":"bool",
               "init":"false",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":80,
               "name":"whatever",
               "category":"attribute",
               "type":"dynamic",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":90,
               "name":"web",
               "category":"attribute",
               "type":"Uri",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":100,
               "name":"other",
               "category":"attribute",
               "type":"Other",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":110,
               "name":"note",
               "category":"attribute",
               "type":"Description",
               "init":"",
               "essential":false,
               "sensitive":false
            }
         ]
      }
   ],
   "lines":[

   ]
}
''';
  